### ISSUE TITLE
Video forced to 16:9

### ISSUE THREAD

**Issue by leonquest** [MiSTer-LLAPI/SNES_MiSTer#2]
When I turned on llapi mode, it immediately changed my aspect ratio to 16:9. If I enter the video settings and change the aspect ratio to "original" it deactivates llapi mode. I'm using the latest updates on cores and main mister. I'm using a blissterv2 with a snes adapter. I updated the blisster ports prior to testing the core.

**Comment by onthewaveagain** [comment]
Old issue related to conflict with status bits.
